FROM rust:1.88

RUN rustup target add wasm32-unknown-unknown \
 && cargo install trunk --version 0.21.4 --locked \
 && rm -rf /root/.cache/trunk 
WORKDIR /work

CMD ["trunk","watch","--release"]

#CMD ["trunk","serve","--release","--address","0.0.0.0","--port","8081"]
