services:
  api:
    build:
      context: ./rustfolio
      dockerfile: Dockerfile.dev
    working_dir: /app/rustfolio
    env_file:
      - ./.env
    environment:
      RUST_LOG: info
      DATABASE_URL: sqlite:///app/rustfolio/data/dev.db
    command: ["/usr/local/cargo/bin/cargo", "watch", "-x", "run --bin rustfolio"]
    ports:
      - "8080:8080"
    volumes:
      - ./rustfolio:/app/rustfolio:Z
      - dbdata:/app/rustfolio/data
      - cargo-registry:/usr/local/cargo/registry
      - cargo-target:/usr/local/cargo/target

  yew:
    build:
      context: ./rustfolio
      dockerfile: Dockerfile.yew   
    working_dir: /work
    ports:
      - "8081:8081"
    volumes:
      - ./rustfolio:/work:Z   
      - wasm-registry:/usr/local/cargo/registry
      - wasm-target:/usr/local/cargo/target

  app:
    build:
      context: ./rustfolio
      dockerfile: Dockerfile
    image: rustfolio:prod
    ports:
      - "8080:8080"
    profiles: ["prod"]

volumes:
  cargo-registry:
  cargo-target:
  wasm-registry:
  wasm-target:
  dbdata:
