services:
  api:
    build:
      context: ./rustfolio
      dockerfile: Dockerfile.dev
    working_dir: /app/rustfolio
    env_file:
      - ./.env
    environment:
      RUST_LOG: info
      DATABASE_URL: sqlite:///app/rustfolio/data/dev.db
    command: ["/usr/local/cargo/bin/cargo", "watch", "-x", "run --bin rustfolio"]
    ports:
      - "8080:8080"
    volumes:
      - ./rustfolio:/app/rustfolio:Z
      - dbdata:/app/rustfolio/data
      - cargo-registry:/usr/local/cargo/registry
      - cargo-target:/usr/local/cargo/target

  yew:
    build:
      context: .
      dockerfile: Dockerfile.yew   # <= on utilise TON Dockerfile.yew
    working_dir: /work
    # IMPORTANT: pas de TRUNK_LOG ici (sinon conflit avec -v du CMD)
    volumes:
      - ./rustfolio/dashboard-spa:/work:Z
      - ./rustfolio/assets:/assets:Z
      - wasm-registry:/root/.cargo/registry
      - wasm-target:/root/target
    # pas de "command:" -> on garde le CMD du Dockerfile.yew
    # ce CMD lance: trunk watch --release --dist /assets/dashboard ...

  app:
    build:
      context: ./rustfolio
      dockerfile: Dockerfile
    image: rustfolio:prod
    ports:
      - "8080:8080"
    profiles: ["prod"]

volumes:
  cargo-registry:
  cargo-target:
  wasm-registry:
  wasm-target:
  dbdata:
