services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/web-hello
    command: ["/usr/local/cargo/bin/cargo", "watch",
              "--poll",
              "-w", "src",
              "-w", "Cargo.toml",
              "--why",
              "-x", "run"]
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:///app/data/app.db
    volumes:
      - ./:/app
      - app-data:/app/data
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target-cache:/app/web-hello/target
    stdin_open: true
    tty: true

volumes:
  cargo-registry:
  cargo-git:
  target-cache:
  app-data: