services:
  dev:
    image: rust:1.80-slim
    working_dir: /app
    volumes:
      - ./:/app
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target-cache:/app/target
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
volumes:
  cargo-registry:
  cargo-git:
  target-cache:
