CREATE TABLE IF NOT EXISTS user_profiles (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  data    TEXT NOT NULL, -- JSON string
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
